from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
import os
from langchain_core.prompts import PromptTemplate
from typing import TypedDict,Annotated, Optional,Literal
from pydantic import BaseModel,EmailStr, Field
# schema

json_schema = {
  "title": "Review",
  "type": "object",
  "properties": {
    "key_themes": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Write down all the key themes discussed in the review in a list"
    },
    "summary": {
      "type": "string",
      "description": "A brief summary of the review"
    },
    "sentiment": {
      "type": "string",
      "enum": ["pos", "neg"],
      "description": "Return sentiment of the review either negative, positive or neutral"
    },
    "pros": {
      "type": ["array", "null"],
      "items": {
        "type": "string"
      },
      "description": "Write down all the pros inside a list"
    },
    "cons": {
      "type": ["array", "null"],
      "items": {
        "type": "string"
      },
      "description": "Write down all the cons inside a list"
    },
    "name": {
      "type": ["string", "null"],
      "description": "Write the name of the reviewer"
    }
  },
  "required": ["key_themes", "summary", "sentiment"]
}
load_dotenv()

# Initialize model
llm = HuggingFaceEndpoint(
    repo_id="meta-llama/Llama-3.1-8B-Instruct",
    task="text-generation",
    huggingfacehub_api_token=os.getenv("HUGGINGFACEHUB_API_TOKEN")
)

model = ChatHuggingFace(llm=llm)
structured_model=model.with_structured_output(json_schema)
review="""
After using the Samsung Galaxy S26 for some time, it feels like a polished flagship device. It focuses more on refinement, AI features, and performance rather than major design or hardware changes. It is reliable for daily use but not a big leap over previous models.

Key Features
Galaxy AI integration for smart assistance, automation, and editing
Powerful processor (Exynos/Snapdragon depending on region) for fast performance
6.3-inch Dynamic AMOLED display with smooth refresh rate
Triple camera setup (50MP main, ultra-wide, telephoto)
Night photography improvements with AI image processing
4300 mAh battery with fast charging
Premium build with Armor Aluminum and Gorilla Glass Victus 2
Water resistance and durable design
One UI software with long-term updates
Pros
Smooth and fast performance in daily use and gaming
Excellent display quality with bright and vibrant colors
Useful AI features that improve productivity and photos
Compact and premium design, easy to hold
Good low-light camera performance
Reliable for multitasking and heavy apps
Strong build quality and durability
Cons
Camera hardware is not a big upgrade compared to older models
Battery life can feel average with heavy usage
Expensive for the level of improvements
Heating or efficiency issues during intense gaming
Feels like an incremental upgrade rather than a major change
Some users report inconsistent camera results in certain conditions

Reviewed by: XYZ ABC
"""
res=structured_model.invoke(review)
print(res)
# res is an dictionary with the keys as defined in the json schema and the value as the output generated by the model.